/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudiosIndexRouteImport } from './routes/audios/index'
import { Route as AudiosAudioIdRouteImport } from './routes/audios/$audioId'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authProfileRouteImport } from './routes/(auth)/profile'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiosIndexRoute = AudiosIndexRouteImport.update({
  id: '/audios/',
  path: '/audios/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiosAudioIdRoute = AudiosAudioIdRouteImport.update({
  id: '/audios/$audioId',
  path: '/audios/$audioId',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authProfileRoute = authProfileRouteImport.update({
  id: '/(auth)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof authLoginRoute
  '/profile': typeof authProfileRoute
  '/register': typeof authRegisterRoute
  '/audios/$audioId': typeof AudiosAudioIdRoute
  '/audios': typeof AudiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof authLoginRoute
  '/profile': typeof authProfileRoute
  '/register': typeof authRegisterRoute
  '/audios/$audioId': typeof AudiosAudioIdRoute
  '/audios': typeof AudiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/profile': typeof authProfileRoute
  '/(auth)/register': typeof authRegisterRoute
  '/audios/$audioId': typeof AudiosAudioIdRoute
  '/audios/': typeof AudiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/register'
    | '/audios/$audioId'
    | '/audios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/register'
    | '/audios/$audioId'
    | '/audios'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(auth)/login'
    | '/(auth)/profile'
    | '/(auth)/register'
    | '/audios/$audioId'
    | '/audios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  authLoginRoute: typeof authLoginRoute
  authProfileRoute: typeof authProfileRoute
  authRegisterRoute: typeof authRegisterRoute
  AudiosAudioIdRoute: typeof AudiosAudioIdRoute
  AudiosIndexRoute: typeof AudiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audios/': {
      id: '/audios/'
      path: '/audios'
      fullPath: '/audios'
      preLoaderRoute: typeof AudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audios/$audioId': {
      id: '/audios/$audioId'
      path: '/audios/$audioId'
      fullPath: '/audios/$audioId'
      preLoaderRoute: typeof AudiosAudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/profile': {
      id: '/(auth)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  authLoginRoute: authLoginRoute,
  authProfileRoute: authProfileRoute,
  authRegisterRoute: authRegisterRoute,
  AudiosAudioIdRoute: AudiosAudioIdRoute,
  AudiosIndexRoute: AudiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
