services:
  postgres:
    image: postgres
    container_name: web_audio_db
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-web-audio}

  minio:
    image: quay.io/minio/minio
    container_name: web_audio_storage
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-minioUser}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-minioPassword}
    volumes:
      - ~/minio/data:/data
    command:
      - server
      - /data
      - --console-address
      - ":9001"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development # or production
      CLIENT_ORIGIN: http://localhost:3000
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-password}@postgres:5432/${DB_NAME:-web-audio}

      JWT_SECRET: someverylongsecretforjwtsession
      SESSION_SECRET: someverylongsecretforcookiesession

      MINIO_ENDPOINT: minio
      MINIO_PUBLIC_ENDPOINT: localhost
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_USER:-minioUser}
      MINIO_SECRET_KEY: ${MINIO_PASSWORD:-minioPassword}

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:5000
    depends_on:
      - server
    ports:
      - 3000:3000
